name: iwrqk
description: Unofficial Iwara Flutter Client.

publish_to: "none"
version: 2.1.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  get: ^4.6.6

  # local storage
  get_storage: ^2.1.1
  flutter_secure_storage: ^10.0.0-beta.4
  path_provider: ^2.1.1
  path: ^1.8.3

  # ui
  dynamic_color: ^1.6.9
  flutter_displaymode: ^0.6.0
  flutter_smart_dialog: ^4.9.6
  easy_refresh: ^3.3.4
  animations: ^2.0.11
  auto_size_text: ^3.0.0

  # i18n
  slang: ^4.7.3
  slang_flutter: ^4.7.0
  flutter_localizations:
    sdk: flutter

  # network
  dio: ^5.4.0
  queue: ^3.1.0+2
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  #cloudflare_interceptor: ^0.0.3
  cloudflare_interceptor:
    git:
      url: https://github.com/h-sumiya/cloudflare_interceptor-fix.git
      ref: main
  http: ^1.4.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  html: ^0.15.6

  # utils
  package_info_plus: ^8.3.0
  logger: ^2.0.2+1
  device_info_plus: ^11.5.0
  permission_handler: ^12.0.1
  url_launcher: ^6.2.2
  markdown_widget: ^2.3.2+3
  photo_view: ^0.15.0
  share_plus: ^11.0.0
  listen_sharing_intent: ^1.9.2
  open_file: ^3.3.2

  # download
  file_picker: ^10.2.0
  flutter_downloader: ^1.11.6

  # pl_player
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  screen_brightness: ^2.1.5
  flutter_volume_controller: ^1.3.1
  audio_video_progress_bar: ^2.0.1
  easy_debounce: ^2.0.3
  auto_orientation_v2: ^2.3.6
  audio_service: ^0.18.12
  audio_session: ^0.2.2
  floating: ^6.0.0

  # desktop
  window_manager: ^0.5.1
  background_downloader: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
  adaptive_icon_monochrome: "assets/launcher/foreground.png"
  windows:
    generate: true
    image_path: "assets/launcher/icon.png"
  macos:
    generate: true
    image_path: "assets/launcher/icon.png"
